stages:
    - build
    
variables:
    VLC_UBUNTU_IMAGE: registry.videolan.org/vlc-ubuntu-bionic:20190627090437

vlc-rs-build:
    tags:
        - docker
        - amd64
    stage: build
    image:
        name: $VLC_UBUNTU_IMAGE
    script:
        - curl https://sh.rustup.rs -sSf | sh -s -- -y
        - source $HOME/.cargo/env
        - curl https://artifacts.videolan.org/vlc/nightly-win32/20201018-0423/vlc-4.0.0-dev-win32-2e6870c2.7z -o build.7z
        - 7z x build.7z
        - rm -rf build.7z
        - export PKG_CONFIG_PATH="$PWD/vlc-4.0.0-dev/sdk/lib/pkgconfig"
        - cargo build --all
